spring.application.name=backend-noAuth
spring.data.mongodb.uri=mongodb+srv://roshanem1772:XWktoRoGzpxoUJiU@sep-cluster.1ykbgfq.mongodb.net/?retryWrites=true&w=majority&appName=SEP-Cluster
spring.data.mongodb.database=SEP-db
server.port=8081

#spring.data.mongodb.uri=mongodb+srv://root1:abc12345@telusko-spring.z9txlr0.mongodb.net/?retryWrites=true&w=majority&appName=Telusko-spring
#spring.data.mongodb.database=telusko

spring.security.user.name=root
spring.security.user.password=root
google.maps.api.key=AIzaSyCd_5naVx6MeeUG3SmBohA04jzOvmAIDgo

myapp.custom.zone.count=5

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

stripe.secretKey = sk_test_51P3IVyRuSnE9X1fnB4Wp4nUnHBslT1lywbLMeRDuN5rfmuTHrkMRNyUrBeFVAb0XIaSyn03peVln4wgiYiBzMPSW00avXY8RKy
stripe.currency=usd
stripe.webhookSecret=whsec_5aaRkRVslGBrHWWFz6uWUaAMSncCvsFv