spring.application.name=backend-noAuth
spring.data.mongodb.uri=mongodb+srv://roshanem1772:4rf5mC7HaXuT5uG4@sep-cluster.1ykbgfq.mongodb.net/?retryWrites=true&w=majority&appName=SEP-Cluster
spring.data.mongodb.database=SEP-db
server.port=8081

#spring.data.mongodb.uri=mongodb+srv://root1:abc12345@telusko-spring.z9txlr0.mongodb.net/?retryWrites=true&w=majority&appName=Telusko-spring
#spring.data.mongodb.database=telusko

spring.security.user.name=root
spring.security.user.password=root
google.maps.api.key=AIzaSyBbjF0HeGK-nW2YxLu27QDxVXQQeDvQjAU