spring.application.name=backend-noAuth
spring.data.mongodb.uri=mongodb+srv://roshanem1772:XWktoRoGzpxoUJiU@sep-cluster.1ykbgfq.mongodb.net/?retryWrites=true&w=majority&appName=SEP-Cluster
spring.data.mongodb.database=SEP-db
server.port=8081
spring.security.user.name=root
spring.security.user.password=root
google.maps.api.key=AIzaSyCd_5naVx6MeeUG3SmBohA04jzOvmAIDgo

myapp.custom.zone.count=5
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

stripe.secretKey = sk_test_51P3IVyRuSnE9X1fnalJbUmpMrhIIhTGZDpaOVzremrZSVyalalf0PLMxroW4ig9NIiuEdadCLXH91nWBpVmQBDKQ00s3HbHRiJ
stripe.currency=usd
stripe.webhookSecret=whsec_5eJyMDX6xcjIQFt876C8AmiaqtHwD4Xi

spring.mail.host=smtp.gmail.com
spring.mail.username=sep.postoffice@gmail.com
spring.mail.password=fabmvaobrfsaqdev
spring.mail.port=587
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.auth=true



#-------------------------
#use this for database unit testing

#spring.application.name=backend-noAuth
#spring.data.mongodb.uri=mongodb+srv://roshanem1772:ypsxrKAfgQdCrEYx@sep-cluster.1ykbgfq.mongodb.net/?retryWrites=true&w=majority&appName=SEP-Cluster
#server.port=8081
#
#spring.security.user.name=root
#spring.security.user.password=root
#google.maps.api.key=AIzaSyBbjF0HeGK-nW2YxLu27QDxVXQQeDvQjAU
#
#myapp.custom.zone.count=5
#spring.servlet.multipart.max-file-size=2MB
#spring.servlet.multipart.max-request-size=2MB
#stripe.secretKey = sk_test_51P3IVyRuSnE9X1fnB4Wp4nUnHBslT1lywbLMeRDuN5rfmuTHrkMRNyUrBeFVAb0XIaSyn03peVln4wgiYiBzMPSW00avXY8RKy
#stripe.currency=usd
#
#spring.data.mongodb.port=0
#spring.data.mongodb.database=testdb
#-------------------------


#---------------------------------------------
#use this for database integration testing

#spring.application.name=backend-noAuth
#server.port=8081
#spring.security.user.name=root
#spring.security.user.password=root
#spring.servlet.multipart.max-file-size=2MB
#spring.servlet.multipart.max-request-size=2MB
#myapp.custom.zone.count=5
#google.maps.api.key=TEST_API_KEY
#stripe.secretKey = sk_test_51P3IVyRuSnE9X1fnB4Wp4nUnHBslT1lywbLMeRDuN5rfmuTHrkMRNyUrBeFVAb0XIaSyn03peVln4wgiYiBzMPSW00avXY8RKy
#stripe.currency=usd
#--------------------------------------------


#------------------------------------------------------
#use this for database backing up
#mongodb.backup.path=F:sep


#------------------------------------------------------

