name: Trigger auto deployment for backend-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ deployment-v0.1 ]
    paths:
    - '**'
    - '.github/workflows/backend-2-AutoDeployTrigger-f55d9092-d39d-481d-83d1-0df359f24b1e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BACKEND2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BACKEND2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BACKEND2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: : ./Dockerfile
          registryUrl: postofficemisregistry.azurecr.io
          registryUsername: ${{ secrets.BACKEND2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BACKEND2_REGISTRY_PASSWORD }}
          containerAppName: backend-2
          resourceGroup: SEP_G12
          imageToBuild: postofficemisregistry.azurecr.io/backend-2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


