name: Trigger auto deployment for backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ deployment-v0.1 ]
    paths:
      - '**'
      - '.github/workflows/backend-AutoDeployTrigger-bfef4767-c3f0-4374-9a25-77903c9d8d58.yml'

  # Allow manual trigger 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the OIDC JWT Token
      contents: read # Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: /home/runner/work/Post-Office-MIS-admin-backend/src  # Adjusted path to the application root directory
          dockerfilePath: /home/runner/work/Post-Office-MIS-admin-backend/Dockerfile  # Adjusted path to your Dockerfile
          registryUrl: postofficemisregistry.azurecr.io
          registryUsername: ${{ secrets.BACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BACKEND_REGISTRY_PASSWORD }}
          containerAppName: backend
          resourceGroup: SEP_G12
          imageToBuild: postofficemisregistry.azurecr.io/backend:${{ github.sha }}
          buildArguments: |  # Optional: add build arguments if needed
            ARG1=value1
            ARG2=value2